name: Test Dandi-Cli Integration

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - 3.6
          - 3.7
          - 3.8
    steps:
    - name: Check out source code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install "dandi[test]"
        python -m pip install -r util/rewrite-dandi-docker.req.txt
    - name: Rewrite dandi docker-compose.py
      run: |
        python util/rewrite-dandi-docker.py
    - name: Run tests
      run: |
        python -m pytest -s -v -k test_parse_dandi --pyargs dandi
